import { Box, styled } from "@mui/material";

export const StyledSidebar = styled(Box)(({ theme }) => ({
  //backgroundColor:'#fff',
  //borderRadius: '4px',
  //boxShadow: '0 0 9px 2px rgba(8,9,10,.07)',
  //padding: '0px',
  //position: 'relative',
  //width: '26.9%',
  //float: 'left',
  //display: 'flex',
  //justifyContent: 'flex-start',
  //alignItems: 'center',
  //flexDirection: 'column',
  //minHeight: '100%',
  //overflow: 'hidden',
  //overflowY: 'auto',
  //width: '420px',
  //maxWidth: '420px',
  //overflowY: 'scroll',
  //backgroundColor: 'gray',
  //[theme.breakpoints.down('sm')]: {
  //  height: "auto",
  //  width: '100%',
  //}
  //overflowY: 'auto',
  //height: '100vh',

  //width: '16.5%',
  //padding: "10px",
  //color: "#ffffffb2",
  //cursor: "default",
  //display: "block",
  //position: "relative",
  //transition: "color 300ms",
  //height: '100%',
  ////background: '#1783db',
  //position: 'fixed',
  ////top: '90px',
  ////left: '90px',
  //color: "white",
  //fontSize: "18px",
  //zIndex: '',
  //overflow: "hidden",
  //overflowY: "scroll",

  //width: "30%",
  //padding: "10px",
  color: "#ffffffb2",
  cursor: "default",
  display: "block",
  //position: "relative",
  transition: "color 300ms",
  height: "90%",
  //background: "#1783db",
  //position: "fixed",
  top: "90px",
  //left: "90px",
  //color: "white",
  fontSize: "18px",
  //zIndex: "",
  overflow: "hidden",
  overflowY: "scroll",

  backgroundColor: theme.mode.background,
  //boxShadow: "rgb(1 5 3 / 25%) 0 0 15px -6px, rgb(0 0 0 / 30%) 0 0 5px -1px",
  //padding: '10px',

}));
